### ISSUE TITLE
sharp is huge!

### ISSUE THREAD

**Issue by hipstersmoothie** [zouhir/lqip#8]
it really takes a long time to download. by far my biggest dep right now. is it possible to use https://github.com/oliver-moran/jimp instead? or at least allow a config option to use a different renderer.

**Comment by lovell** [comment]
Hello, https://github.com/lovell/sharp/issues/1301 should help with this.

**Comment by styfle** [comment]
Looks like the tables have turned, and now sharp is smaller than jimp.

jimp: [![jimp size](https://packagephobia.com/badge?p=jimp@0.16.1)](https://packagephobia.com/result?p=jimp@0.16.1)

sharp: [![install size](https://packagephobia.com/badge?p=sharp@0.26.3)](https://packagephobia.com/result?p=sharp@0.26.3)
